# 系统配置
system:
  #系统对外端口
  outside-http-addr: "127.0.0.1:20000"
  #内部通信端口
  inside-http-addr: "127.0.0.1:20001"

  web-http-addr: "127.0.0.1:8989"
  # 超时单位秒
  timeout-second : 10



# redis configuration
redis:
  db: 1
  addr: "127.0.0.1:6379"
  password: ""



# 日志参数
zap:
  level: debug
  prefix: '[game_balance]'
  format: json
  director: log
  encode-level: LowercaseLevelEncoder
  stacktrace-key: stacktrace
  max-age: 30
  show-line: true
  log-in-console: true

balance:
  formula: "-(user_num * 10 + cpu*2)"
  max_time_out_sec: 30
  check_time_out_sec: 60
